dist: trusty
language: python
python: 3.6
cache: pip
env:
  - TOX_ENV=py36
  - TOX_ENV=flake8
install:
  - pip install tox
before_script:
  - make version-file
script:
  - tox -e $TOX_ENV
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
