swagger: "2.0"
info:
  description: >
    PollBot is an hardworking little robot (microservice) that frees
    its human masters from the toilsome task of polling for the state
    of things during the Firefox release process.
  version: "1.0.0"
  title: "Mozilla Product Delivery PollBot"
  contact:
    url: "irc://irc.mozilla.org:6696/#product-delivery"
  license:
    name: "Mozilla Public License 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "pollbot.services.mozilla.com"
basePath: "/v1"
schemes:
- "https"

parameters:
  product:
    name: "product"
    in: "path"
    description: "Mozila Product name (i.e firefox, thunderbird, fennec)"
    required: true
    type: "string"
  version:
    name: "version"
    in: "path"
    description: "version of the given product to check for (i.e 52.0.1)"
    required: true
    type: "string"

paths:
  /{product}/{version}/archive:
    get:
      summary: "checks if the product version archive is downloadable"
      operationId: "checkArchiveExistance"
      produces:
      - "application/json"
      parameters:
      - $ref: "#/parameters/versionId"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/existanceStatus"

  /{product}/{version}/product-details:
    get:
      summary: "checks version exists in product-details.mozilla.org"
      description: >
        checks https://product-details.mozilla.org/1.0/firefox.json for the
        specific version
      operationId: "checkProductDetailsExistance"
      produces:
      - "application/json"
      parameters:
      - $ref: "#/parameters/versionId"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/existanceStatus"

  /{product}/{version}/bedrock/security-advisories:
    get:
      summary: "check security advisories have been published on mozilla.org"
      operationId: "checkBedrockSecurityAdvisoryExistance"
      produces:
      - "application/json"
      parameters:
      - $ref: "#/parameters/versionId"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/existanceStatus"

  /{product}/{version}/bedrock/download-links:
    get:
      summary: "check download links have been published on mozilla.org"
      operationId: "checkBedrockDownloadLinkExistance"
      produces:
      - "application/json"
      parameters:
      - $ref: "#/parameters/versionId"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/existanceStatus"
  /{product}/{version}/bedrock/release-notes:
    get:
      summary: "check release notes have been published on mozilla.org"
      operationId: "checkBedrockReleaseNotesExistance"
      produces:
      - "application/json"
      parameters:
      - $ref: "#/parameters/versionId"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/existanceStatus"

definitions:
  existanceStatus:
    type: "object"
    required:
    - "status"
    properties:
      status:
        type: "string"
        description: "current status of the resource"
        enum:
        - "missing"
        - "incomplete"
        - "exists"
        - "error"
      message:
        type: "string"
        description: "error message"

externalDocs:
  description: "Find out more about PollBot"
  url: "http://github.com/mozilla/PollBot"
